"""Update HHQResponse model with enhanced fields

Revision ID: 4386c3ef7389
Revises: 
Create Date: 2025-03-22 13:10:48.123783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4386c3ef7389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hhq_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_token', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('responses', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_modified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_hhq_response_token', ['unique_token'])
        batch_op.drop_column('q1')
        batch_op.drop_column('q2')
        batch_op.drop_column('q5')
        batch_op.drop_column('q4')
        batch_op.drop_column('q3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hhq_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q3', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('q4', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('q5', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('q2', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('q1', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('uq_hhq_response_token', type_='unique')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('last_modified_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('status')
        batch_op.drop_column('responses')
        batch_op.drop_column('unique_token')

    # ### end Alembic commands ###
